
    create table EMAIL_NOTIFICATION (
        EMAIL_NOTIFICATION_ID bigint generated by default as identity,
        content varchar(10240),
        FROM_EMAIL_ADDRESS varchar(512),
        subject varchar(1024),
        primary key (EMAIL_NOTIFICATION_ID)
    );

    create table FILE (
        FILE_ID bigint generated by default as identity,
        fileLock_FILE_LOCK_ID bigint,
        fileSpecs_FILE_SPECS_ID bigint,
        fileType_FILE_TYPE_ID bigint,
        primary key (FILE_ID)
    );

    create table FILE_LOCK (
        FILE_LOCK_ID bigint generated by default as identity,
        LOCK_MOMENT bigint,
        LOCKER_ID varchar(50),
        LOCKER_PROCES varchar(50),
        primary key (FILE_LOCK_ID)
    );

    create table FILE_SPECS (
        FILE_SPECS_ID bigint generated by default as identity,
        FILE_NAME varchar(255),
        FILE_PATCH varchar(1024),
        FILE_SIZE bigint,
        primary key (FILE_SPECS_ID)
    );

    create table FILE_STATUS (
        FILE_STATUS_ID bigint generated by default as identity,
        moment bigint,
        status varchar(30),
        JOINED_FILE_ID bigint,
        primary key (FILE_STATUS_ID)
    );

    create table FILE_TIME_MANAGEMENT (
        FILE_TIME_MANAGEMENT_ID bigint generated by default as identity,
        KEEP_FILE_AFTER_DOWNLOADING_FOR_DAYS integer,
        KEEP_FILE_FOR_DAYS integer,
        WAIT_FOR_SOMETHING_FOR_DAYS integer,
        primary key (FILE_TIME_MANAGEMENT_ID)
    );

    create table FILE_TYPE (
        FILE_TYPE_ID bigint generated by default as identity,
        discription varchar(500),
        fileKind integer,
        FILE_NAME_REGEXP_MATCHER varchar(255),
        name varchar(20),
        emailNotification_EMAIL_NOTIFICATION_ID bigint,
        fileTimeManagement_FILE_TIME_MANAGEMENT_ID bigint,
        gftKanaal_GFT_KANAAL_ID bigint,
        primary key (FILE_TYPE_ID)
    );

    create table GFT_KANAAL (
        GFT_KANAAL_ID bigint generated by default as identity,
        KANAAL_NAAM varchar(50),
        primary key (GFT_KANAAL_ID)
    );

    create unique index UK_qo086v9srqx86fpf4kcryl5se on FILE_TYPE (name);

    alter table FILE 
        add constraint FK_vsyyqp5ulsmvtrw93dek5lt4 
        foreign key (fileLock_FILE_LOCK_ID) 
        references FILE_LOCK;

    alter table FILE 
        add constraint FK_7fqlqehbblxtaint91bf9iuxi 
        foreign key (fileSpecs_FILE_SPECS_ID) 
        references FILE_SPECS;

    alter table FILE 
        add constraint FK_1jcovdvt8r3flqflrsee3c99x 
        foreign key (fileType_FILE_TYPE_ID) 
        references FILE_TYPE;

    alter table FILE_STATUS 
        add constraint FK_my1y8wkaodsrebxy78t9ppghh 
        foreign key (JOINED_FILE_ID) 
        references FILE;

    alter table FILE_TYPE 
        add constraint FK_n7ly94ov1ijw2y3kcr9jkn4u3 
        foreign key (emailNotification_EMAIL_NOTIFICATION_ID) 
        references EMAIL_NOTIFICATION;

    alter table FILE_TYPE 
        add constraint FK_dohqx3m2wpggv5k977wes6ns4 
        foreign key (fileTimeManagement_FILE_TIME_MANAGEMENT_ID) 
        references FILE_TIME_MANAGEMENT;

    alter table FILE_TYPE 
        add constraint FK_43qwe7dy0rygw4lwbmtvn0v8h 
        foreign key (gftKanaal_GFT_KANAAL_ID) 
        references GFT_KANAAL;
