
    create table Email_Notification (
        id bigint generated by default as identity,
        content varchar(10240),
        fromEmailAddress varchar(512),
        subject varchar(1024),
        primary key (id)
    );

    create table File (
        File_ID bigint generated by default as identity,
        fileLock_id bigint,
        fileSpecs_id bigint,
        fileType_File_Type_ID bigint,
        primary key (File_ID)
    );

    create table File_File_Status (
        File_File_ID bigint not null,
        history_File_Status_ID bigint not null
    );

    create table File_Lock (
        id bigint generated by default as identity,
        lockMoment bigint,
        lockerId varchar(50),
        lockerProces varchar(50),
        primary key (id)
    );

    create table File_Specs (
        id bigint generated by default as identity,
        fileName varchar(255),
        filePath varchar(1024),
        fileSize bigint,
        primary key (id)
    );

    create table File_Status (
        File_Status_ID bigint generated by default as identity,
        moment bigint,
        status varchar(30),
        primary key (File_Status_ID)
    );

    create table File_Time_Management (
        id bigint generated by default as identity,
        keepFileAfterDownloadingForDays integer,
        keepFileForDays integer,
        waitForSomethingForDays integer,
        primary key (id)
    );

    create table File_Type (
        File_Type_ID bigint generated by default as identity,
        discription varchar(500),
        fileKind integer,
        fileNameRegExpMatcher varchar(255),
        name varchar(20),
        emailNotification_id bigint,
        fileTimeManagement_id bigint,
        gftKanaal_id bigint,
        primary key (File_Type_ID)
    );

    create table GFT_Kanaal (
        id bigint generated by default as identity,
        kanaalNaam varchar(50),
        fileType_File_Type_ID bigint,
        primary key (id)
    );

    alter table File_File_Status 
        add constraint UK_doorvtp56w2co1dnult5328lo unique (history_File_Status_ID);

    create unique index UK_d47l7m0wtutghwjlfx5s1pemp on File_Type (name);

    alter table File 
        add constraint FK_l0u84lj3gl20i9hat3pcwvum3 
        foreign key (fileLock_id) 
        references File_Lock;

    alter table File 
        add constraint FK_a4xcipqjbe9kudfs2pm3ia69e 
        foreign key (fileSpecs_id) 
        references File_Specs;

    alter table File 
        add constraint FK_h3xos72ycqr59ai03o7nilhvh 
        foreign key (fileType_File_Type_ID) 
        references File_Type;

    alter table File_File_Status 
        add constraint FK_doorvtp56w2co1dnult5328lo 
        foreign key (history_File_Status_ID) 
        references File_Status;

    alter table File_File_Status 
        add constraint FK_9joj57esovgaudi601pojli48 
        foreign key (File_File_ID) 
        references File;

    alter table File_Type 
        add constraint FK_4xopkmhi8ma6sht94v9qx17fu 
        foreign key (emailNotification_id) 
        references Email_Notification;

    alter table File_Type 
        add constraint FK_8y6byj7y04hsy8tbls9agl09b 
        foreign key (fileTimeManagement_id) 
        references File_Time_Management;

    alter table File_Type 
        add constraint FK_htuxlgsug8eqojek3r602dlkw 
        foreign key (gftKanaal_id) 
        references GFT_Kanaal;

    alter table GFT_Kanaal 
        add constraint FK_n4k51v9ses94553hopymbadqj 
        foreign key (fileType_File_Type_ID) 
        references File_Type;
